name: pubsingnal
description: A new Flutter package project.
version: 0.0.1
author: Yeison Hernandez
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  meta: ^1.2.4
  pointycastle: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
